p.prf = {};

// Fill defaults.
p.prfFilFxn = function(k,v){
	p.prfEA.forEach(prfE=>{
		p.prf[prfE.sltS] = prfE.dflM;});};

//
p.prfRcvFxn = function(){
	var o = sto.lde({sltS:"prf"});
	if (o.staF === T){
		π.ooas(p.prf,o.datM);}};

// Save to local-storage.
p.prfSveAllFxn = function(){
	var o = sto.sve({sltS:"prf",datM:p.prf});};

// [!] [251,258] were skipped somehow. Use those first.
p.prfEA = [
	{ sltS:   "1" , lblS:"Note Offset"                              , untS:"Seconds"                                      , dflM:0                                                                                                                                   , ifcE:{typS:"slider",minN:-1,maxN:1,snpN:0.001}    , hlpS:"More-positive means notes will appear later (more delay) compared to audio. Technical note: In some implementations, audio may be reverse-offset instead of notes being offset." },
	{ sltS:   "2" , lblS:"Scroll Speed"                             , untS:"Screens-Per-Second"                           , dflM:1.1                                                                                                                                 , ifcE:{typS:"slider",minN:0,maxN:6,snpN:0.001}     , hlpS:""                                                                                                                                                                                },
	{ sltS:   "3" , lblS:"Volume"                                   , untS:"Unitless-Multiplier:[0,1]"                    , dflM:0.65                                                                                                                                , ifcE:{typS:"slider",minN:0,maxN:1,snpN:0.001}     , hlpS:""                                                                                                                                                                                },
	{ sltS:   "6" , lblS:"Judgement Line Position"                  , untS:"Multiplier-Of-Lane-Height-Offset-From-Bottom" , dflM:0.15                                                                                                                                , ifcE:{typS:"slider",minN:0,maxN:1,snpN:0.001}     , hlpS:""                                                                                                                                                                                },
	{ sltS:   "7" , lblS:"Lane Aspect Ratio"                        , untS:"Width-Divided-By-Height-Ratio"                , dflM:0.075                                                                                                                               , ifcE:{typS:"slider",minN:0,maxN:1,snpN:0.001}     , hlpS:""                                                                                                                                                                                },
	{ sltS:   "5" , lblS:"Note Head Height"                         , untS:"Multiplier-Of-Lane-Height"                    , dflM:0.015                                                                                                                               , ifcE:{typS:"slider",minN:0,maxN:0.05,snpN:0.0001} , hlpS:""                                                                                                                                                                                },
	{ sltS:   "4" , lblS:"Lane Divider Width"                       , untS:"Multiplier-Of-Lane-Width"                     , dflM:0.015                                                                                                                               , ifcE:{typS:"slider",minN:0,maxN:0.25,snpN:0.001}  , hlpS:""                                                                                                                                                                                },
	{ sltS: "260" , lblS:"Bar Height"                               , untS:"Multiplier-Of-Lane-Height"                    , dflM:0.005                                                                                                                               , ifcE:{typS:"slider",minN:0,maxN:0.05,snpN:0.0001} , hlpS:""                                                                                                                                                                                },
	{ sltS: "261" , lblS:"Snap Height"                              , untS:"Multiplier-Of-Lane-Height"                    , dflM:0.0025                                                                                                                              , ifcE:{typS:"slider",minN:0,maxN:0.05,snpN:0.0001} , hlpS:""                                                                                                                                                                                },
	{ sltS:  "41" , lblS:"1-Key Key Layout"                         , untS:"Array-Of-Key-Code"                            , dflM:["Space|0"]                                                                                                                         , ifcE:{typS:"key-array"}                           , hlpS:""                                                                                                                                                                                },
	{ sltS:  "42" , lblS:"2-Key Key Layout"                         , untS:"Array-Of-Key-Code"                            , dflM:["KeyA|0","KeyS|0"]                                                                                                                 , ifcE:{typS:"key-array"}                           , hlpS:""                                                                                                                                                                                },
	{ sltS:  "43" , lblS:"3-Key Key Layout"                         , untS:"Array-Of-Key-Code"                            , dflM:["KeyA|0","KeyS|0","KeyD|0"]                                                                                                        , ifcE:{typS:"key-array"}                           , hlpS:""                                                                                                                                                                                },
	{ sltS:  "44" , lblS:"4-Key Key Layout"                         , untS:"Array-Of-Key-Code"                            , dflM:["KeyA|0","KeyS|0","KeyD|0","KeyF|0"]                                                                                               , ifcE:{typS:"key-array"}                           , hlpS:""                                                                                                                                                                                },
	{ sltS:  "45" , lblS:"5-Key Key Layout"                         , untS:"Array-Of-Key-Code"                            , dflM:["KeyA|0","KeyS|0","KeyD|0","KeyF|0","KeyG|0"]                                                                                      , ifcE:{typS:"key-array"}                           , hlpS:""                                                                                                                                                                                },
	{ sltS:  "46" , lblS:"6-Key Key Layout"                         , untS:"Array-Of-Key-Code"                            , dflM:["KeyA|0","KeyS|0","KeyD|0","KeyF|0","KeyG|0","KeyH|0"]                                                                             , ifcE:{typS:"key-array"}                           , hlpS:""                                                                                                                                                                                },
	{ sltS:   "0" , lblS:"7-Key Key Layout"                         , untS:"Array-Of-Key-Code"                            , dflM:["KeyA|0","KeyS|0","KeyD|0","KeyF|0","KeyG|0","KeyH|0","KeyJ|0"]                                                                    , ifcE:{typS:"key-array"}                           , hlpS:""                                                                                                                                                                                },
	{ sltS:  "47" , lblS:"8-Key Key Layout"                         , untS:"Array-Of-Key-Code"                            , dflM:["KeyA|0","KeyS|0","KeyD|0","KeyF|0","KeyG|0","KeyH|0","KeyJ|0","KeyK|0"]                                                           , ifcE:{typS:"key-array"}                           , hlpS:""                                                                                                                                                                                },
	{ sltS:  "48" , lblS:"9-Key Key Layout"                         , untS:"Array-Of-Key-Code"                            , dflM:["KeyA|0","KeyS|0","KeyD|0","KeyF|0","KeyG|0","KeyH|0","KeyJ|0","KeyK|0","KeyL|0"]                                                  , ifcE:{typS:"key-array"}                           , hlpS:""                                                                                                                                                                                },
	{ sltS:  "49" , lblS:"10-Key Key Layout"                        , untS:"Array-Of-Key-Code"                            , dflM:["KeyA|0","KeyS|0","KeyD|0","KeyF|0","KeyG|0","KeyH|0","KeyJ|0","KeyK|0","KeyL|0","Semicolon|0"]                                    , ifcE:{typS:"key-array"}                           , hlpS:""                                                                                                                                                                                },
	{ sltS:  "50" , lblS:"11-Key Key Layout"                        , untS:"Array-Of-Key-Code"                            , dflM:["KeyA|0","KeyS|0","KeyD|0","KeyF|0","KeyG|0","KeyH|0","KeyJ|0","KeyK|0","KeyL|0","Semicolon|0","Quote|0"]                          , ifcE:{typS:"key-array"}                           , hlpS:""                                                                                                                                                                                },
	{ sltS: "250" , lblS:"Reset"                                    , untS:"Key-Code"                                     , dflM:"KeyO|0"                                                                                                                            , ifcE:{typS:"key"}                                 , hlpS:"Press this key at any time to reset the most recently loaded chart."                                                                                                             },
	{ sltS:  "31" , lblS:"Play"                                     , untS:"Key-Code"                                     , dflM:"KeyQ|0"                                                                                                                            , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS:  "32" , lblS:"Pause"                                    , untS:"Key-Code"                                     , dflM:"KeyW|0"                                                                                                                            , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS:  "55" , lblS:"Increase Volume"                          , untS:"Key-Code"                                     , dflM:"ArrowRight|0|A"                                                                                                                    , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS:  "56" , lblS:"Decrease Volume"                          , untS:"Key-Code"                                     , dflM:"ArrowLeft|0|A"                                                                                                                     , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS:  "57" , lblS:"Scroll Speed Increase"                    , untS:"Key-Code"                                     , dflM:"(+)"                                                                                                                               , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS:  "58" , lblS:"Scroll Speed Decrease"                    , untS:"Key-Code"                                     , dflM:"(-)"                                                                                                                               , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS:  "37" , lblS:"Snap Finer"                               , untS:"Key-Code"                                     , dflM:"ArrowRight|0"                                                                                                                      , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS:  "38" , lblS:"Snap Coarser"                             , untS:"Key-Code"                                     , dflM:"ArrowLeft|0"                                                                                                                       , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS:  "51" , lblS:"Composer Mode Enable"                     , untS:"Key-Code"                                     , dflM:"KeyC|0"                                                                                                                            , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS:  "52" , lblS:"Composer Mode Disable"                    , untS:"Key-Code"                                     , dflM:"KeyC|0|S"                                                                                                                          , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS:  "33" , lblS:"[Composer Mode] Scroll Forward One Bar"   , untS:"Key-Code"                                     , dflM:"ArrowUp|0|S"                                                                                                                       , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS:  "35" , lblS:"[Composer Mode] Scroll Forward One Snap"  , untS:"Key-Code"                                     , dflM:"ArrowUp|0"                                                                                                                         , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS:  "34" , lblS:"[Composer Mode] Scroll Backward One Bar"  , untS:"Key-Code"                                     , dflM:"ArrowDown|0|S"                                                                                                                     , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS:  "36" , lblS:"[Composer Mode] Scroll Backward One Snap" , untS:"Key-Code"                                     , dflM:"ArrowDown|0"                                                                                                                       , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS: "251" , lblS:"[Composer Mode] Scroll To Beginning"      , untS:"Key-Code"                                     , dflM:"Period|0"                                                                                                                          , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS: "265" , lblS:"[Composer Mode] Scroll To End"            , untS:"Key-Code"                                     , dflM:"Period|0|S"                                                                                                                        , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS: "252" , lblS:"[Composer Mode] Scroll To 0% (Beginning)" , untS:"Key-Code"                                     , dflM:"Digit0|0|A"                                                                                                                        , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS: "253" , lblS:"[Composer Mode] Scroll To 10%"            , untS:"Key-Code"                                     , dflM:"Digit1|0|A"                                                                                                                        , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS: "254" , lblS:"[Composer Mode] Scroll To 20%"            , untS:"Key-Code"                                     , dflM:"Digit2|0|A"                                                                                                                        , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS: "255" , lblS:"[Composer Mode] Scroll To 30%"            , untS:"Key-Code"                                     , dflM:"Digit3|0|A"                                                                                                                        , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS: "256" , lblS:"[Composer Mode] Scroll To 40%"            , untS:"Key-Code"                                     , dflM:"Digit4|0|A"                                                                                                                        , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS: "257" , lblS:"[Composer Mode] Scroll To 50%"            , untS:"Key-Code"                                     , dflM:"Digit5|0|A"                                                                                                                        , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS: "258" , lblS:"[Composer Mode] Scroll To 60%"            , untS:"Key-Code"                                     , dflM:"Digit6|0|A"                                                                                                                        , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS: "262" , lblS:"[Composer Mode] Scroll To 70%"            , untS:"Key-Code"                                     , dflM:"Digit7|0|A"                                                                                                                        , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS: "263" , lblS:"[Composer Mode] Scroll To 80%"            , untS:"Key-Code"                                     , dflM:"Digit8|0|A"                                                                                                                        , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS: "264" , lblS:"[Composer Mode] Scroll To 90%"            , untS:"Key-Code"                                     , dflM:"Digit9|0|A"                                                                                                                        , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS:  "29" , lblS:"[Composer Mode] Note Head Place/Remove"   , untS:"Array-Of-Key-Code"                            , dflM:["Digit1|0","Digit2|0","Digit3|0","Digit4|0","Digit5|0","Digit&|0","Digit7|0","Digit8|0","Digit9|0","Digit0|0"]                     , ifcE:{typS:"key-array"}                           , hlpS:"Beginning of a note (hit notes don't have an explicit end)."                                                                                                                     },
	{ sltS:  "30" , lblS:"[Composer Mode] Note Tail Place/Remove"   , untS:"Array-Of-Key-Code"                            , dflM:["Digit1|0|S","Digit2|0|S","Digit3|0|S","Digit4|0|S","Digit5|0|S","Digit&|0|S","Digit7|0|S","Digit8|0|S","Digit9|0|S","Digit0|0|S"] , ifcE:{typS:"key-array"}                           , hlpS:"End of a note (for hold notes only)."                                                                                                                                            },
	{ sltS:  "53" , lblS:"[Composer Mode] Time Speed Up"            , untS:"Key-Code"                                     , dflM:"ArrowRight|0|S"                                                                                                                    , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS:  "54" , lblS:"[Composer Mode] Time Slow Down"           , untS:"Key-Code"                                     , dflM:"ArrowLeft|0|S"                                                                                                                     , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS:  "25" , lblS:"[Composer Mode] BPM Place"                , untS:"Key-Code"                                     , dflM:"KeyB|0"                                                                                                                            , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS:  "28" , lblS:"[Composer Mode] BPM Remove"               , untS:"Key-Code"                                     , dflM:"KeyB|0|S"                                                                                                                          , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS:  "26" , lblS:"[Composer Mode] BPM Increase (Large)"     , untS:"Key-Code"                                     , dflM:"ArrowUp|0|A|S"                                                                                                                     , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS:  "27" , lblS:"[Composer Mode] BPM Increase (Small)"     , untS:"Key-Code"                                     , dflM:"ArrowUp|0|A"                                                                                                                       , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS:  "23" , lblS:"[Composer Mode] BPM Decrease (Large)"     , untS:"Key-Code"                                     , dflM:"ArrowDown|0|A|S"                                                                                                                   , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	{ sltS:  "24" , lblS:"[Composer Mode] BPM Decrease (Small)"     , untS:"Key-Code"                                     , dflM:"ArrowDown|0|A"                                                                                                                     , ifcE:{typS:"key"}                                 , hlpS:""                                                                                                                                                                                },
	//{
	//	sltS : "",
	//	lblS : "",
	//	untS : "",
	//	dflM : ,
	//	ifcE : {typS:""},
	//	hlpS : "",},
	];

π.a(1,11).forEach(lneC=>{
	p.prfEA.push({ sltS:[U, "76", "95","114","133","152","171",  "8","190", "39","209","228"][lneC] , lblS:str(lneC)+"-Key Judgement Line Color (Neutral)"   , untS:"Array-Of-HSLA-Each:[0,1]" , dflM:π.a(0,lneC-1).map(lneN=>((n,c)=>[π.round(n/c,6),1  ,0.5   ,1     ])(lneN,lneC)) , ifcE:{typS:"color-array"} , hlpS:"Horizontal indicator for when to press."                });
	p.prfEA.push({ sltS:[U, "77", "96","115","134","153","172",  "9","191", "59","210","229"][lneC] , lblS:str(lneC)+"-Key Judgement Line Color (Activated)" , untS:"Array-Of-HSLA-Each:[0,1]" , dflM:π.a(0,lneC-1).map(lneN=>((n,c)=>[π.round(n/c,6),1  ,0.85  ,1     ])(lneN,lneC)) , ifcE:{typS:"color-array"} , hlpS:"Horizontal indicator for when to press, while pressed." });
	p.prfEA.push({ sltS:[U, "78", "97","116","135","154","173", "10","192", "60","211","230"][lneC] , lblS:str(lneC)+"-Key Background Color (Neutral)"       , untS:"Array-Of-HSLA-Each:[0,1]" , dflM:π.a(0,lneC-1).map(lneN=>((n,c)=>[π.round(n/c,6),0.5,0.5   ,0.0625])(lneN,lneC)) , ifcE:{typS:"color-array"} , hlpS:""                                                       });
	p.prfEA.push({ sltS:[U, "79", "98","117","136","155","174", "11","193", "61","212","231"][lneC] , lblS:str(lneC)+"-Key Background Color (Activated)"     , untS:"Array-Of-HSLA-Each:[0,1]" , dflM:π.a(0,lneC-1).map(lneN=>((n,c)=>[π.round(n/c,6),1  ,0.5   ,0.15  ])(lneN,lneC)) , ifcE:{typS:"color-array"} , hlpS:"While pressed."                                         });
	p.prfEA.push({ sltS:[U, "80", "99","118","137","156","175", "12","194", "62","213","232"][lneC] , lblS:str(lneC)+"-Key Drag Color (Deactivated)"         , untS:"Array-Of-HSLA-Each:[0,1]" , dflM:π.a(0,lneC-1).map(lneN=>((n,c)=>[π.round(n/c,6),1  ,0.35  ,0.5   ])(lneN,lneC)) , ifcE:{typS:"color-array"} , hlpS:"[UNUSED]"                                               });
	p.prfEA.push({ sltS:[U, "81","100","119","138","157","176", "13","195", "63","214","233"][lneC] , lblS:str(lneC)+"-Key Drag Color (Neutral)"             , untS:"Array-Of-HSLA-Each:[0,1]" , dflM:π.a(0,lneC-1).map(lneN=>((n,c)=>[π.round(n/c,6),1  ,0.5   ,0.5   ])(lneN,lneC)) , ifcE:{typS:"color-array"} , hlpS:"[UNUSED]"                                               });
	p.prfEA.push({ sltS:[U, "82","101","120","139","158","177", "14","196", "64","215","234"][lneC] , lblS:str(lneC)+"-Key Drag Color (Activated)"           , untS:"Array-Of-HSLA-Each:[0,1]" , dflM:π.a(0,lneC-1).map(lneN=>((n,c)=>[π.round(n/c,6),1  ,0.85  ,0.5   ])(lneN,lneC)) , ifcE:{typS:"color-array"} , hlpS:"Tracks press durations."                                });
	p.prfEA.push({ sltS:[U, "83","102","121","140","159","178", "15","197", "65","216","235"][lneC] , lblS:str(lneC)+"-Key Lane Divider Color (Neutral)"     , untS:"Array-Of-HSLA-Each:[0,1]" , dflM:π.a(0,lneC-1).map(lneN=>((n,c)=>[π.round(n/c,6),0.5,0.125 ,1     ])(lneN,lneC)) , ifcE:{typS:"color-array"} , hlpS:"Vertical lines on both sides."                          });
	p.prfEA.push({ sltS:[U, "84","103","122","141","160","179", "16","198", "66","217","236"][lneC] , lblS:str(lneC)+"-Key Lane Divider Color (Activated)"   , untS:"Array-Of-HSLA-Each:[0,1]" , dflM:π.a(0,lneC-1).map(lneN=>((n,c)=>[π.round(n/c,6),1  ,0.125 ,1     ])(lneN,lneC)) , ifcE:{typS:"color-array"} , hlpS:"Vertical lines on both sides, while pressed."           });
	p.prfEA.push({ sltS:[U, "85","104","123","142","161","180", "17","199", "67","218","237"][lneC] , lblS:str(lneC)+"-Key Note Head Color (Deactivated)"    , untS:"Array-Of-HSLA-Each:[0,1]" , dflM:π.a(0,lneC-1).map(lneN=>((n,c)=>[π.round(n/c,6),1  ,0.5   ,0.5   ])(lneN,lneC)) , ifcE:{typS:"color-array"} , hlpS:"After note passes."                                     });
	p.prfEA.push({ sltS:[U, "86","105","124","143","162","181", "18","200", "40","219","238"][lneC] , lblS:str(lneC)+"-Key Note Head Color (Neutral)"        , untS:"Array-Of-HSLA-Each:[0,1]" , dflM:π.a(0,lneC-1).map(lneN=>((n,c)=>[π.round(n/c,6),1  ,0.5   ,1     ])(lneN,lneC)) , ifcE:{typS:"color-array"} , hlpS:"While note approaches."                                 });
	p.prfEA.push({ sltS:[U, "87","106","125","144","163","182", "19","201", "68","220","239"][lneC] , lblS:str(lneC)+"-Key Note Head Color (Activated)"      , untS:"Array-Of-HSLA-Each:[0,1]" , dflM:π.a(0,lneC-1).map(lneN=>((n,c)=>[π.round(n/c,6),1  ,0.85  ,1     ])(lneN,lneC)) , ifcE:{typS:"color-array"} , hlpS:"While note is triggered."                               });
	p.prfEA.push({ sltS:[U, "88","107","126","145","164","183", "20","202", "69","221","240"][lneC] , lblS:str(lneC)+"-Key Note Trickle Color (Deactivated)" , untS:"Array-Of-HSLA-Each:[0,1]" , dflM:π.a(0,lneC-1).map(lneN=>((n,c)=>[π.round(n/c,6),1  ,0.5   ,0.1875])(lneN,lneC)) , ifcE:{typS:"color-array"} , hlpS:"After note passes."                                     });
	p.prfEA.push({ sltS:[U, "89","108","127","146","165","184", "21","203", "70","222","241"][lneC] , lblS:str(lneC)+"-Key Note Trickle Color (Neutral)"     , untS:"Array-Of-HSLA-Each:[0,1]" , dflM:π.a(0,lneC-1).map(lneN=>((n,c)=>[π.round(n/c,6),1  ,0.5   ,0.375 ])(lneN,lneC)) , ifcE:{typS:"color-array"} , hlpS:"While note approaches."                                 });
	p.prfEA.push({ sltS:[U, "90","109","128","147","166","185", "22","204", "71","223","242"][lneC] , lblS:str(lneC)+"-Key Note Trickle Color (Activated)"   , untS:"Array-Of-HSLA-Each:[0,1]" , dflM:π.a(0,lneC-1).map(lneN=>((n,c)=>[π.round(n/c,6),1  ,0.85  ,0.375 ])(lneN,lneC)) , ifcE:{typS:"color-array"} , hlpS:"While note is triggered"                                });
	p.prfEA.push({ sltS:[U, "91","110","129","148","167","186","247","205", "72","224","243"][lneC] , lblS:str(lneC)+"-Key Bar Color (Neutral)"              , untS:"Array-Of-HSLA-Each:[0,1]" , dflM:π.a(0,lneC-1).map(lneN=>((n,c)=>[π.round(n/c,6),0  ,0.85  ,0.85  ])(lneN,lneC)) , ifcE:{typS:"color-array"} , hlpS:"Major horizontal line."                                 });
	p.prfEA.push({ sltS:[U, "92","111","130","149","168","187","248","206", "73","225","244"][lneC] , lblS:str(lneC)+"-Key Bar Color (Activated)"            , untS:"Array-Of-HSLA-Each:[0,1]" , dflM:π.a(0,lneC-1).map(lneN=>((n,c)=>[π.round(n/c,6),0  ,0.85  ,0.85  ])(lneN,lneC)) , ifcE:{typS:"color-array"} , hlpS:"Major horizontal line, while pressed."                  });
	p.prfEA.push({ sltS:[U, "93","112","131","150","169","188","249","207", "74","226","245"][lneC] , lblS:str(lneC)+"-Key Snap Color (Neutral)"             , untS:"Array-Of-HSLA-Each:[0,1]" , dflM:π.a(0,lneC-1).map(lneN=>((n,c)=>[π.round(n/c,6),0  ,0.5   ,0.85  ])(lneN,lneC)) , ifcE:{typS:"color-array"} , hlpS:"Minor horizontal line."                                 });
	p.prfEA.push({ sltS:[U, "94","113","132","151","170","189","259","208", "75","227","246"][lneC] , lblS:str(lneC)+"-Key Snap Color (Activated)"           , untS:"Array-Of-HSLA-Each:[0,1]" , dflM:π.a(0,lneC-1).map(lneN=>((n,c)=>[π.round(n/c,6),0  ,0.5   ,0.85  ])(lneN,lneC)) , ifcE:{typS:"color-array"} , hlpS:"Minor horizontal line, while pressed."                  });
	});